---
apiVersion: v1
kind: Template
metadata:
  name: postigrade
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: postigrade
  spec:
    envName: ${ENV_NAME}
    deployments:
    #
    # Component cloudigrade-postigrade deployment:
    #
    - name: svc
      minReplicas: ${{POSTIGRADE_MIN_REPLICAS}}
      revisionHistoryLimit: 10
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - /probe-liveness.sh
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - /probe-readiness.sh
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: ${POSTIGRADE_LIMITS_CONTAINER_CPU_REQUEST}
            memory: ${POSTIGRADE_LIMITS_CONTAINER_MEM_REQUEST}
          limits:
            cpu: ${POSTIGRADE_LIMITS_CONTAINER_CPU_LIMIT}
            memory: ${POSTIGRADE_LIMITS_CONTAINER_MEM_LIMIT}
    database:
      sharedDbAppName: cloudigrade
      version: 12
    dependencies:
    - cloudigrade

parameters:
- name: IMAGE
  displayName: Postigrade Image
  required: true
  value: quay.io/cloudservices/postigrade
- name: IMAGE_TAG
  displayName: Postigrade Image tag
  required: true
  value: latest
- name: POSTIGRADE_LIMITS_CONTAINER_MEM_LIMIT
  displayName: Postigrade Container Memory Limit
  required: true
  value: 256Mi
- name: POSTIGRADE_LIMITS_CONTAINER_MEM_REQUEST
  displayName: Postigrade Container Memory Request
  required: true
  value: 128Mi
- name: POSTIGRADE_LIMITS_CONTAINER_CPU_LIMIT
  displayName: Postigrade Container CPU Limit
  required: true
  value: 400m
- name: POSTIGRADE_LIMITS_CONTAINER_CPU_REQUEST
  displayName: Postigrade Container CPU Request
  required: true
  value: 200m
- name: ENV_NAME
  description: ClowdEnv Name
  required: true
- name: POSTIGRADE_MIN_REPLICAS
  description: Minimum number of replicas to run
  required: true
  value: '1'
