apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/cloudigrade/postigrade?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: postigrade
    appstudio.openshift.io/component: postigrade
    pipelines.appstudio.openshift.io/type: build
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/docker-build-oci-ta.yaml
  name: postigrade-on-push
  namespace: teamnado-konflux-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/teamnado-konflux-tenant/postigrade:{{revision}}
  - name: dockerfile
    value: Dockerfile
  taskRunSpecs:
    - pipelineTaskName: sast-shell-check
      stepSpecs:
        - name: sast-shell-check
          computeResources:
            requests:
              memory: 2Gi
            limits:
              memory: 8Gi
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-postigrade
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
