name: Tag

env:
  IMAGE_NAME: quay.io/cloudservices/postigrade
  IMAGE_NAME_COMMIT: quay.io/cloudservices/postigrade:${{ github.sha }}

on:
  release:
    types:
      - created

jobs:
  test-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from $IMAGE_NAME:latest .

  deploy-build-and-push-tagged-image:
    name: Build and Push Tagged Image
    env:
      COMMIT_TAG: ${{ github.event.release.tag_name }}
      QUAY_BOT_USERNAME: ${{ secrets.QUAY_BOT_USERNAME }}
      QUAY_BOT_TOKEN: ${{ secrets.QUAY_BOT_TOKEN}}
    needs: [test-docker]
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${QUAY_BOT_TOKEN}" | docker login quay.io -u ${QUAY_BOT_USERNAME} --password-stdin
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${COMMIT_TAG} .
      - run: docker push ${IMAGE_NAME}:${COMMIT_TAG}
